# Generated by Django 5.2.7 on 2025-10-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('position', models.CharField(max_length=200, verbose_name='Cargo/Posición')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('content', models.TextField(verbose_name='Testimonio')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Foto')),
                ('rating', models.IntegerField(default=5, help_text='1-5 estrellas', verbose_name='Calificación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['-created_at'],
            },
        ),
    ]
