# Generated by Django 5.2.7 on 2026-04-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Destacado'),
        ),
    ]
