services:
  - type: web
    name: portfolio-django
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health/
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "joseftf1991@gmail.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "ContraseñaStrong!123"

databases:
  - name: portfolio-db
    databaseName: portfolio_db
    user: portfolio_user
    plan: free