# Generated by Django 5.2.7 on 2025-10-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('title', models.CharField(max_length=200, verbose_name='Título profesional')),
                ('bio', models.TextField(verbose_name='Biografía')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Foto de perfil')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/', verbose_name='CV (PDF)')),
            ],
            options={
                'verbose_name': 'Sobre Mí',
                'verbose_name_plural': 'Sobre Mí',
            },
        ),
    ]
