# Generated by Django 5.2.7 on 2025-10-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='techs/', verbose_name='Ícono')),
                ('proficiency', models.IntegerField(default=50, help_text='0-100', verbose_name='Nivel de dominio (%)')),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Base de Datos'), ('tools', 'Herramientas'), ('other', 'Otros')], max_length=50, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Tecnología',
                'verbose_name_plural': 'Tecnologías',
                'ordering': ['category', 'name'],
            },
        ),
    ]
