# Generated by Django 5.2.7 on 2025-10-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['category', '-proficiency', 'name'], 'verbose_name': 'Tecnología', 'verbose_name_plural': 'Tecnologías'},
        ),
        migrations.AddField(
            model_name='technology',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Ej: devicon-python-plain colored', max_length=200, verbose_name='Clase del icono (DevIcon)'),
        ),
    ]
